### PR TITLE
refactored slack folder location code to include new path

### PR DESCRIPTION
**Pull request by Dzejms**

### CODE REVIEW

**Comment by Cromzinc** [comment]
Some people will have multiple instances of slack installed (eg cboston), so it would be nice for this to have options to select which install or just patch all of them.

**Comment by Dzejms** [comment]
> Some people will have multiple instances of slack installed (eg cboston), so it would be nice for this to have options to select which install or just patch all of them.

Tell cboston to not be weird.

**Comment by c-boston** [comment]
Lol I only had to install the second instance because the original PS script couldn't find the slack directory

**Comment by Cromzinc** [comment]
Cool story for real - but did you delete the first install?

**Comment by c-boston** [comment]
Be right back....

**Comment by Dzejms** [comment]
If it's the windows store install, yeah, that's gonna need another pass. I uninstalled from there because the path was crazy. From the slack website or from chocolatey should work now (hopefully).

**Comment by marchica** [comment]
Awesome! Thanks @Dzejms

**Pull request merged**
